### ISSUE TITLE
Write vandy importer code in atlascope-vandy-importer plugin

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#11]
The code for importing a source uri for a dataset that uses the "vandy" importer should be in `atlascope_plugins/atlascope-vandy-importer/import_function.py`.

**Comment by annehaley** [comment]
The importer function should return a tuple of `(imported_data_file, metadata_dicitonary)`.

**Comment by mcovalt** [comment]
Did https://github.com/atlascope/atlascope/pull/10 close this?

**Comment by annehaley** [comment]
Not yet, #10 just added the infrastructure for writing the function that this issue is referring to. #10 just left that function as a print statement for @marySalvi to replace.

**Comment by waxlamp** [comment]
@marySalvi, can you provide an update on this? You can edit the main issue description if necessary.

**Comment by marySalvi** [comment]
Hopefully this will be resolved tomorrow. The importer properly gets a token and downloads the image. #4 will engage with the importer as well so both should be resolved tomorrow.
