### ISSUE TITLE
Multiple relationships between Investigation and Dataset

### ISSUE THREAD

**Issue by naglepuff** [atlascope/atlascope#110]
With our current data model, `Datasets` can be related to an `Investigation` in a couple of ways.

1. Via the `Investigation.datasets` property
2. Via a `DatasetEmbedding` as either a `DatasetEmbedding.parent` or `DatasetEmbedding.child`

I imagine that eventually we want to ensure that for all of an Investigation's embeddings, the `parent` and `child` datasets are also included in (1).

**Comment by waxlamp** [comment]
In our meeting this week, we discussed reinterpreting `Investigation.datasets` as the list of all "root" datasets for an investigation. The main way this interpretation will show up in Atlascope is by displaying all the root datasets side by side in the Investigation detail view, and by using these roots as the basis on which to create the dataset embedding trees.
