### ISSUE TITLE
Create an s3 importer plugin and use that as the default

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#15]
This may be a one-to-two-liner function; we may also want some dummy processor functions for this plugin, too.

**Comment by waxlamp** [comment]
The importer's job is to bring data into the system from outside, so in my view this issue is all about creating an "upload importer"--that is, an importer that allows you to upload a file from disk to S3, then creates the appropriate Dataset object from it.

Is that what you were thinking of too, @annehaley?

**Comment by annehaley** [comment]
Originally, this idea had been that we would require the user to already have a file on s3 to reference with the `source_uri` field, but this was before we added a `content` field to the Dataset model. With the addition of the `content` field and making the `source_uri` field nullable, A user can already choose to either directly upload the file or point to it. Therefore, we do not need a default importer anymore, and this issue can be closed.

**Comment by waxlamp** [comment]
Do we have the infrastructure ready to support uploading files from the frontend?

**Comment by annehaley** [comment]
Yes, the girder cookicutter project came ready with those endpoints. However, we decided not to add a "Create Dataset" endpoint at this point, choosing instead to create db objects on the backend and fetch them on the frontend.

**Comment by waxlamp** [comment]
Ah, I see. Yeah that's a good approach--we can stuff data in programmatically (via the populate script) and be on our way developing the research features. At some point we'll want that "create dataset" button so I'll file an issue, but it's low priority at the moment.
