### ISSUE TITLE
Download once, populate many times workflow

### ISSUE THREAD

**Issue by waxlamp** [atlascope/atlascope#152]
Since we are reaching the point of working with "real" data at O(GB) sizes, we will need a way to avert too much downloading of data as we work. I'd like to see a "download once, populate many times" workflow. Essentially, the dev will be responsible for downloading test data to a specific location on disk (which can be a git-ignored directory in the cloned Atlascope repository), and the populate script should have a mode where it "uploads" data from that directory to Atlascope, etc. This mode should be idempotent, which may make it a bit tricky, but it doesn't seem like anything too crazy to address.

As a first example we should use the colon image from Vandy Explorer:
- Girder item: https://styx.neurology.emory.edu/girder/#item/61fbe6214874d4ffdf1c8569
- Vandy Explorer: https://vanderbilt.digitalslidearchive.net/#!top/multichannel_view:id=61fbe6214874d4ffdf1c8569:group=0

This would be in addition to the other data import modes we have been working with. It doesn't necessarily need to be a new first-class import mode in Atlascope itself, if it's accomplishable by other means (i.e., tricks in the populate script).

**Comment by mcovalt** [comment]
Resonant GeoData uses [pooch](https://github.com/fatiando/pooch). Here's the module for files fetched by pooch: [datastore.py](https://github.com/ResonantGeoData/ResonantGeoData/blob/5731363beed551d6984cbc8b9fe9d6e9b9894c38/django-rgd/rgd/datastore.py). The files are downloaded and cached in the user's home directory. This cache can be persisted in CI tests. Here's an example where Resonant GeoData calls pooch: [data_fixtures.py](https://github.com/ResonantGeoData/ResonantGeoData/blob/5731363beed551d6984cbc8b9fe9d6e9b9894c38/django-rgd-imagery/tests/data_fixtures.py#L15).

There's also [GitLFS](https://git-lfs.github.com/). It requires the developer to have the extension installed. It's advantage compared to pooch is using GitHub's bandwidth and availability, but this is a paid service so we'd need to figure out billing.

**Comment by waxlamp** [comment]
Pooch seems like a great solution to this.

It seems like creating a registry (as in the RGD example) and including a small script that does the Pooch retrieval stuff that we can run as part of the dev environment startup should cover our use cases. Do you agree, @mcovalt?

**Comment by mcovalt** [comment]
I think that sounds good. I'll start on a PR.

**Comment by mcovalt** [comment]
Reopening as I didn't include the image https://styx.neurology.emory.edu/girder/#item/61fbe6214874d4ffdf1c8569 in my PR #159.
