### ISSUE TITLE
Processor plugins

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#16]
Alongside importer plugins, we should create processor plugins that run on a raw Dataset after import to create a derived dataset. Any raw Dataset can link to zero or more derived Datasets. For phase 1, the actual processor functions can be simple and useless.

**Comment by waxlamp** [comment]
I'd say for phase 1 the processor functions can be a *mix* of "useless", demo functions, and ones that drive our phase 1 use case workflows.

**Comment by waxlamp** [comment]
@annehaley, we have a working job running infrastructure in place, along with a couple of "dummy" computational routines, right? That is probably enough to call this closed--we can add more such processor modules alongside those dummy ones. What do you think?

**Comment by annehaley** [comment]
Absolutely. we just changed the name for what was originally discussed as "processors" to "jobs". Closing with reference to #26.
