### ISSUE TITLE
Research tile stack concepts

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#17]
It is unclear how we can adapt the tile stack concept to non-geographical data for our custom concept of the semantic zoom. The scope of this issue is to compile research on the possibilities.

**Comment by annehaley** [comment]
Here is an example of tiling a simple image into 2 zoom levels: https://gherardo.shinyapps.io/exampleLocalTiles/
and the repo used for that: https://github.com/gherardovarando/Map_tools

**Comment by waxlamp** [comment]
When we put images from different sources into different levels of a given `Investigation`'s "tile stack", we will have control over how that serving happens; in particular, if we want to simply designate landmarks that represent the same "geographical" point in two different datasets, that would be a simple way for us to get a coherent concept of zooming between two different images.

**Comment by annehaley** [comment]
A Phase I implementation for this could be hard-coding corresponding points in images; a Phase II implementation may need to involve computer vision on these images (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5729285/).

**Comment by waxlamp** [comment]
@annehaley, what's the "next action" on this issue?

This seems to be something @mcovalt is already looking into as part of the general need to involve different scales of biological data in the same instance of tile service; can you confirm, Matt?

**Comment by annehaley** [comment]
If we agree that an appropriate Phase 1 implementation would be hard-coding corresponding points in images, the next step would be to close this issue and open a new one for creating a collection of Datasets in our `populate` script to which we can add these hard-coded point relationships. This should allow us to zoom in on one Dataset and see another appear in its context.

**Comment by waxlamp** [comment]
> If we agree that an appropriate Phase 1 implementation would be hard-coding corresponding points in images, the next step would be to close this issue and open a new one for creating a collection of Datasets in our `populate` script to which we can add these hard-coded point relationships. This should allow us to zoom in on one Dataset and see another appear in its context.

This is one good idea among several. We can discuss at today's meeting but my understanding is that @mcovalt has been thinking about this. I have an idea for how we can accelerate the research process, funneling workable ideas into the codebase.

**Comment by mcovalt** [comment]
> This seems to be something @mcovalt is already looking into as part of the general need to involve different scales of biological data in the same instance of tile service; can you confirm, Matt?

Yes. I believe the best approach is to have multiple layers defined in GeoJS. Each of these layers use a tiling endpoint specific to their dataset. I will write a design document describing an approach to how these layers can be transformed so that their coordinates represent relationships between other layers.

**Comment by waxlamp** [comment]
With @mcovalt's demo of the embedded datasets concept, I think this can be closed.
