### ISSUE TITLE
GeoDjango for storage of Pin locations

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#18]

**Comment by waxlamp** [comment]
Who is working on this one? Seems to be @mcovalt--could you give an update?

**Comment by mcovalt** [comment]
GeoDjango is ready to be used. All that needs to be done is adding a [`PointField`](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/model-api/#pointfield) to the [`Pin` model](https://github.com/atlascope/atlascope/blob/9f01330f770b53e2cbe1fe5fc644bdbe4d104d67/atlascope/core/models/pin.py#L23). I will make the PR.

**Comment by waxlamp** [comment]
I'll close this because it's a design consideration within other features we're contemplating (so handled better as part of those issues).
