### ISSUE TITLE
`s3_file_field` related exception on Dataset admin page

### ISSUE THREAD

**Issue by mcovalt** [atlascope/atlascope#28]
The following exception is thrown when visiting the `Dataset` admin page:

```
's3_file_field' is not a registered namespace
```

I believe we need to [add the relevant URL](https://github.com/atlascope/atlascope/blob/01cee820f6be48b2484be18d6cfbdb91329d71bc/atlascope/urls.py#L36).

**Comment by annehaley** [comment]
Apologies, the change to uncomment this line in `urls.py` got lost in a commit squash. Putting it back in #30.
