### ISSUE TITLE
Create Job endpoints

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#29]
We don't need endpoints for the `JobRunOutputImage` model, since it will be hidden implementation behind the `JobRun` model.

Endpoints we need for Phase 1:

1. List available JobScript objects
2. Create and run JobRun object
3. Re-run existing JobRun object
4. List existing JobRun objects
5. Get details for existing JobRun object

Endpoints we can implement later in Phase 2:

1. Create new JobScript object
2. Edit existing JobScript object
3. Delete existing JobScript object
4. Delete existing JobRun object

**Comment by waxlamp** [comment]
@annehaley, what's the status of this? (Mainly so I can set it as "in progress" if you're actively working on it, or close it if it's done.)

**Comment by annehaley** [comment]
In had informally assigned this to @marySalvi previously, but given she already has other tasking and I don't, I'll self-assign this now and we can consider it In-Progress.
