### ISSUE TITLE
configure communication between API and client 

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#3]
The client and API should be served by separate services (potentially two docker images). The frontend will need an API communication module added to it.

**Comment by waxlamp** [comment]
> The client and API should be served by separate services (potentially two docker images).

We've been well-served by docker-for-backend/yarn-for-frontend; no need for dockerizing the frontend.

> The frontend will need an API communication module added to it.

If you're describing a typescript file that encapsulates API calls, I can see that being useful, but I want to evaluate that in light of the frontend team's needs, so I'm going to close this issue.
