### ISSUE TITLE
Cannot login with password "123"

### ISSUE THREAD

**Issue by mcovalt** [atlascope/atlascope#40]
According to the README, I should be able to login with password "123" by default. This doesn't seem to work.

**Comment by naglepuff** [comment]
The default password for the `populate` command was changed in 6fa5c2d0c6c4ed194ff9760a6f920767d897361d
Could we update the `README` in #32?

**Comment by mcovalt** [comment]
I think we can update the README sans PR. Is this OK to do @waxlamp?

**Comment by waxlamp** [comment]
> I think we can update the README sans PR. Is this OK to do @waxlamp?

I think it's best to do it through a PR, even if that seems like overkill. You can "self-review" the PR, however.
