### ISSUE TITLE
Make default OAuth 2.0 client type "public" for development

### ISSUE THREAD

**Issue by mcovalt** [atlascope/atlascope#41]
The OAuth 2.0 application created by default uses the "confidential" OAuth 2.0 client type. We need a "public" client type in development for our frontend to speak to the backend over unencrypted HTTP.

**Comment by waxlamp** [comment]
@mcovalt, could you give more information on this? I'm surprised this happens by default since we're using stock Girder4 for this project. Do other projects need to worry about this as well?

**Comment by mcovalt** [comment]
This issue was created after walking through #38 with @naglepuff. I _think_ they were referencing a guide from another Girder 4 project. Is that right, @naglepuff? Which project was that?

**Comment by naglepuff** [comment]
That's correct. I was following the guide [here](https://github.com/multinet-app/multinet-api#setup-oauth-login) from Multinet.

**Comment by waxlamp** [comment]
The Multinet guide says to switch the type to Public, so I'm confused what this issue is saying to do.

**Comment by mcovalt** [comment]
This issue is requesting that the type be set to public by default for development environments so that the manual change isn't required.

**Comment by mcovalt** [comment]
This seems to be done: https://github.com/atlascope/atlascope/blob/fe6cafb80ff3734d962593292b73c9d5bb987194/atlascope/core/management/commands/populate.py#L73.
