### ISSUE TITLE
Make default OAuth 2.0 client redirect URL be http://localhost:8080 for development

### ISSUE THREAD

**Issue by mcovalt** [atlascope/atlascope#43]
Right now it defaults to http://localhost:8081. It can be anything, but usually the client listens on http://localhost:8080.

**Comment by waxlamp** [comment]
@mcovalt, where does that default come from?

**Comment by naglepuff** [comment]
https://github.com/atlascope/atlascope/blob/dd583f2f03da2c13b98112c60e7f537e49e0c5f3/atlascope/core/management/commands/populate.py#L24
