### ISSUE TITLE
Display Vandy data in an Investigation detail view

### ISSUE THREAD

**Issue by waxlamp** [atlascope/atlascope#46]
- Select a suitable image from Vandy Explorer
- coordinate with @marySalvi on how to import that data into the system
- Implement InvestigationDetail logic to show data via tile service

**Comment by waxlamp** [comment]
One good idea might be to set up two investigations, each with a different image, to illustrate the intended day-to-day working of this aspect of the system.

**Comment by naglepuff** [comment]
Closing due to merge of #66
