### ISSUE TITLE
Create endpoints for Pins

### ISSUE THREAD

**Issue by naglepuff** [atlascope/atlascope#56]
Useful endpoints could include:

- Get a pin by ID (include all fields)
- Get all pins associated with an Investigation (include minimal fields like ID + location data)

**Comment by annehaley** [comment]
I put in #61 to add the second one, but we already had the first. For now, I don't think we need two separate serializers for Pins like we have for Investigations. There aren't enough fields on a Pin to warrant a small serializer and a full one.

**Comment by annehaley** [comment]
Should the second endpoint replace the general GET all pins endpoint? It may be reasonable to remove the "all pins" endpoint entirely, since pins would only ever be needed in the context of their investigation.

**Comment by naglepuff** [comment]
> Should the second endpoint replace the general GET all pins endpoint? It may be reasonable to remove the "all pins" endpoint entirely, since pins would only ever be needed in the context of their investigation.

I agree that it would be reasonable to remove the GET all endpoint but I don't think it should hold up #61
