### ISSUE TITLE
Design: JobRuns vs. Side Breakouts

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#60]
This issue is a place to discuss the design for our two planned infrastructures for performing analysis on an image.

JobRuns are done with predefined server-side JobScript objects which are either preloaded into Atlascope or written by the user (Phase 2). These are run upon creation and a re-run can be requested by the user. The outputs are static (images or other) and will be displayed statically to the user.

Breakout Analytics (working title) are done with dynamically-defined client-side scripts. These produce client-side visualizations that can be further adjusted/expanded/continued/etc. One possible implementation that would reduce custom implementation is an embedded Jupyter notebook.

**Comment by waxlamp** [comment]
> JobRuns are done with predefined server-side JobScript objects which are either preloaded into Atlascope or written by the user (Phase 2). These are run upon creation and a re-run can be requested by the user. The outputs are static (images or other) and will be displayed statically to the user.
> 

I think this is a great design for us to build upon. It's simple and gets the job done. Most of our effort should lie in creating instances of these jobs we can imbue with biological meaning.

> Breakout Analytics (working title) are done with dynamically-defined client-side scripts. These produce client-side visualizations that can be further adjusted/expanded/continued/etc. One possible implementation that would reduce custom implementation is an embedded Jupyter notebook.

To align with the terminology already established, we should call these "side breakouts". A Jupyter notebook is a good idea, but I envision that being something launched in a new window rather than embedded in the Atlascope application. For embedded components, we can begin with something like a histogram that displays image pixel statistics, and graduate to something specific to the biological workflows we want to address in Phase 1.

**Comment by waxlamp** [comment]
Can you explain why the title of this issue pits JobRuns against "breakout analytics" (or "side breakouts")? Both are integral parts of the intended functionality.

**Comment by annehaley** [comment]
> Can you explain why the title of this issue pits JobRuns against "breakout analytics" (or "side breakouts")? Both are integral parts of the intended functionality.

The title was meant to connote "compare & contrast," not necessarily which is better

**Comment by waxlamp** [comment]
The way I see us prototyping these things is to offer the user a chance to run a specific analytic on an image (either the whole slide, or some selected section thereof). If the result of that computation is stored (as a pin?) at that location of the image, then when it is visible, the application can offer the user a chance to display one of a selection of side breakout types. We connect the side breakout component to the computed data, and let it do its thing.

Is that a good basic design? (Obviously we would need to flesh out some details, but that can be deferred until the work is underway.) I am largely describing Chapter 2 of our initial user story.

**Comment by annehaley** [comment]
Yes, I agree with your description. What do you imagine as options for the side breakout types?

**Comment by waxlamp** [comment]
Much like the question of "job types", right now I just envision a dummy vis component that just displays something trivial, like the average pixel color or some other braindead stand-in for "real" visualization types that we would cook up later.

I don't know how much we can pre-bake the design for this. It's something that (IMO) requires some experimentation (via collaboration between you and @naglepuff). We can schedule a meeting to talk about this--I have some ideas that I'm perhaps not expressing well in this thread.

**Comment by waxlamp** [comment]
This is a good discussion, but I think after refactoring how we handle jobs, and the need for experimentation to investigate side breakouts, I'm going to close this in favor of #91.
