### ISSUE TITLE
Add API Key field to dataset endpoint

### ISSUE THREAD

**Issue by marySalvi** [atlascope/atlascope#64]
Users will need to the ability to provide and api key for the dataset importer

**Comment by waxlamp** [comment]
I think we'll want to expand the scope of this and rethink how the importers are invoked. I have some ideas, perhaps we can discuss on Monday.

**Comment by annehaley** [comment]
We agreed that we can move the importer functions to `core` (#67). When we redefine them there, we can ensure that the `import` endpoint receives all the arguments that the invoked function requires.

**Comment by waxlamp** [comment]
I think this has been solved; re-open if not.
