### ISSUE TITLE
Move importer functions to `core` app

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#67]
We agreed that the simplest implementation for the importer functions would be regular pythonic functions within `core`, rather than a plugin architecture or a django apps architecture.

**Comment by annehaley** [comment]
To address #64, the definition of importer functions should bubble required arguments to the `import` function when invoked. This may mean checking arguments synchronously before performing the import asynchronously so that missing arguments will cause a descriptive error in the response.

**Comment by waxlamp** [comment]
I think that any necessary arguments to the importer function can be passed as a JSON object in the body of the relevant POST request. Then, the backend can splat that object into the importer function's arguments, and the importer function itself can do whatever checking needs to be done.

We can discuss this more when we meet about this topic.
