### ISSUE TITLE
Add Pins to InvestigationDetail

### ISSUE THREAD

**Issue by naglepuff** [atlascope/atlascope#71]
The investigation detail view currently shows some very basic information about an investigation, including the ability to display any `Dataset` of type `tile_source`.

This view should also display pins for an investigation. Some ideas:
- Display `Pins` in the sidebar. If pins are associated with a derived `Dataset` we could also display pertinent information/visualizations related to that `Dataset`
- Display `Pins` on the `tile_source` `Dataset` for an investigation. This can be done with a feature layer on the `geojs` map, and we could use `geojs` events to drive workflows.  (dependent on resolution of #18)

**Comment by waxlamp** [comment]
Both good ideas. With the current work in flight for the pin model, I think we're on the cusp of being able to experiment with these ideas. @naglepuff I'm assingning this to you, but let me know if you'd prefer someone else to take it.

**Comment by naglepuff** [comment]
@waxlamp I'm happy to take this on.

**Comment by waxlamp** [comment]
Closed by #103.
