### ISSUE TITLE
Enable creation of subimage datasets from the InvestigationDetail view

### ISSUE THREAD

**Issue by naglepuff** [atlascope/atlascope#74]
Since one recurring idea for Phase 1 has been selecting regions of an image and running computations on them, users should be able to somehow select these regions of an image. 

This could look like:
1. User draws a rectangle feature on the image. The user could be prompted to run a job with the rectangle coordinates as inputs
2. User chooses a job that runs on a subimage. Whatever portion of the whole slide image is visible in the viewer is used as the subimage

**Comment by waxlamp** [comment]
We're going more with (1), but deferring the mechanism for running a job. Perhaps we can put together a modal dialog for launching a job on an image or subimage, but let's wait until some of this issue is settled first.

**Comment by annehaley** [comment]
Resolved by #127
