### ISSUE TITLE
Add PUT and POST API endpoints for base models

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#8]
The first 8 endpoints in the API are mostly read-only GET endpoints. Each model will need write endpoints.
This issue is scoped to include the implementation of tests for each new endpoint.

**Comment by waxlamp** [comment]
@annehaley, what's the status of this issue?

If the "baseline" endpoints are all implemented, I think this could be closed in favor of more specific issues addressing specific needs in the API. Let me know what you think.

**Comment by annehaley** [comment]
Sure, we already have the basic endpoints for retrieving information (other than Job-related endpoints, captured in #29), so we can close this in favor of more specific issues later.
