### ISSUE TITLE
Job statuses

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#83]
We need a way to fetch the status of a spawned job. 

Perhaps we could go as far as deleting the object once the run is complete? This would keep this table's storage limited to in-progress jobs, and the outputs and important information about a job are kept in the resulting Dataset that is created. Not sure how the frontend would reconcile this, though; this is just a thought.

**Comment by waxlamp** [comment]
I wouldn't worry about deleting finished jobs at this point.

**Comment by naglepuff** [comment]
What if the `Job` object itself was passed to the celery task? Instead of having a `Job.spawn` method, call `delay` directly in the endpoint, and pass the `Job` object as a parameter? As the task runs, it could update a `status` field on the `Job`.

**Comment by waxlamp** [comment]
That sounds like a good idea. I'm not clear on the status of this issue; could you give an update, @annehaley?

The same PR that addresses this issue could also tackle #90.

**Comment by annehaley** [comment]
In #89, I changed the `spawn` method on Jobs so that the Job object is passed into the celery task as @naglepuff describes, so adding the `status` field and updating it within the celery task is all that is left to close this issue.

**Comment by waxlamp** [comment]
@annehaley I'll go ahead and assign this to you since you have a clear vision for how to get it done. Thanks!
