### ISSUE TITLE
Provide way to link job results with Investigation

### ISSUE THREAD

**Issue by naglepuff** [atlascope/atlascope#84]
My understanding of performing analytics within Atlascope is that this is primarily done with the use of jobs, which will eventually need to be spawned by users from the front end.

This places these jobs within the context of an investigation, and therefore I believe there should be a way to obtain Jobs and job output datasets for a single investigation.

Right now we have `GET /jobs`. From this endpoint, I don't see a clear connection to job results or the investigation from which that job was launched.

We also have `GET /datasets`. Some datasets in the populate script are created by jobs, and this is reflected in the dataset's metadata. However it doesn't include the ID of the job, or the investigation from which this job was spawned.

I think these connections are all useful. Connecting a `Job` to its output (via new tables or more specific metadata) provides additional information about why those `Datasets` exist. Connecting the `Job` to the `Investigation` makes it easier to determine what the system should present to a user when looking at a specific `Investigation`.

@annehaley @waxlamp Interested in hearing your thoughts on this. Or if a solution already exists that I can't seem to find.

**Comment by annehaley** [comment]
I think you're right, and there are definitely places I overlooked the need to specify the context Investigation on other models. I tried again at a class diagram (shown below). I want to be sure we cover all relationship paths before implementation. Are there any relationships we need to access (remember each of these arrows represents a forward relationship, but the API can expose reverse relationships)?

![Atlascope Class Diagram](https://user-images.githubusercontent.com/44912689/155411022-2b598d7a-bbda-4ecd-8a24-11da936ea9ec.png)

**Comment by naglepuff** [comment]
This looks great! Connecting everything back to an `Investigation` is going to be really helpful moving forward. 

Some relationships I know will be handy for jobs are:
- All Jobs for a given Investigation
- All input/output Datasets for a given Job

Those two as relationships would allow the client to display only relevant jobs to a user looking at an investigation, and display the results of those jobs based on the resultant datasets.

Endpoints that expose those relationships would be enough close this issue.
