### ISSUE TITLE
Add frontend code to this repository and set up CI with Heroku & Netlify

### ISSUE THREAD

**Issue by annehaley** [atlascope/atlascope#9]
Don't forget to change the repo name to just `atlascope`!

**Comment by mcovalt** [comment]
The frontend code was brought in by https://github.com/atlascope/atlascope/pull/19. We don't yet have CI/CD with Heroku/Netlify.

**Comment by waxlamp** [comment]
> The frontend code was brought in by #19. We don't yet have CI/CD with Heroku/Netlify.

We're not worrying about cloud hosting yet, so we can ignore that part until it comes up again naturally.

Do we run any tests? If so, I'll file a new issue to put in CI to run them.

**Comment by mcovalt** [comment]
> Do we run any tests?

[GitHub Actions runs linting checks and unit tests for the frontend already](https://github.com/atlascope/atlascope/blob/edc0d62a9961317c12033e874418333039ab6fc8/.github/workflows/web.yml#L39-L42).

**Comment by waxlamp** [comment]
Cool, going to close this since anything left to do will arise naturally as a new issue.
