### ISSUE TITLE
Support "text" datasets for annotating an investigation

### ISSUE THREAD

**Issue by waxlamp** [atlascope/atlascope#92]
_Originally posted by @annehaley in https://github.com/atlascope/atlascope/issues/87#issuecomment-1048103894_:
> A next step would be adding functionality to the frontend to allow the user to place a pin arbitrarily and write a new Dataset with text content to act as a note.

The idea would be to have a dataset type of "note", and include a "text" property in the metadata. A pin involving a note dataset could simply display the associated text on hover, etc.

**Comment by annehaley** [comment]
The Pin model has a `note` text field and the `child` dataset is nullable. Would it suffice to use the Pin like this (no child dataset, just note content) instead of creating a Dataset object just to contain the note? Or is there some use case to do something Dataset-ish with the note?

**Comment by waxlamp** [comment]
> The Pin model has a `note` text field and the `child` dataset is nullable. Would it suffice to use the Pin like this (no child dataset, just note content) instead of creating a Dataset object just to contain the note? Or is there some use case to do something Dataset-ish with the note?

Yeah, the `Pin`'s `note` field seems sufficient. If we didn't do this, we'd have to make the child one of these "note" datasets, right? What's your current vision for how you render the pin's `note` field in-app?

**Comment by annehaley** [comment]
I was thinking pins show up as dots on the context map, and on hover, we can display the content of the `note` field, as well as the info about the `child` dataset if there is one.

**Comment by waxlamp** [comment]
This sounds like a plausible idea. @naglepuff, you've been working on pin display; can you weigh in?

**Comment by naglepuff** [comment]
The "hover to discover" functionality is what I plan to work on next with regards to pin display. I think its a good feature to have, I just need to figure out the "vue" way to do it.

**Comment by waxlamp** [comment]
The "popover mode" of [v-menu](https://vuetifyjs.com/en/components/menus/#popover-menu) is one idea I've used in the past for this sort of thing.

**Comment by naglepuff** [comment]
Closing via #103
